src/BrainCloudClient.cpp
src/mac/nsURLLoader.mm

Changed the destroy method to properly delete the URLSession regardless of the _threadRunning status.

Fix memory leak.

---

src/IBrainCloudComms.cpp

Fixed heartbeat to be 85% of session expiry

---

CMakeLists.txt
cmake/FindUUID.cmake
src/nix/LinuxGUID.cpp
tests/src/TestGUID.cpp
tests/src/TestGUID.h

This will break jenkins, we have to install UUID on it
`sudo apt-get install uuid-dev`

BCLD-3069 Linux GUID + TestGUID

---

CMakeLists.txt
tests/src/TestBCRTTComms.cpp

RTT tests and cmake cleanup

---

include/braincloud/BrainCloudGroup.h
include/braincloud/BrainCloudSocialLeaderboard.h
include/braincloud/BrainCloudVirtualCurrency.h
include/braincloud/ServiceOperation.h
src/BrainCloudGroup.cpp
src/BrainCloudSocialLeaderboard.cpp
src/BrainCloudVirtualCurrency.cpp
src/ServiceOperation.cpp
tests/src/TestBCGroup.cpp
tests/src/TestBCSocialLeaderboard.cpp
tests/src/TestBCVirtualCurrency.cpp

Social leader and group calls to cpp

---

solutions/mac/BrainCloudCpp.xcodeproj/project.pbxproj

* Updated RTT codes
* updating Cpp xcode Project to fix objc compile issues

Adding CPP files to xcode project for mac

---

BrainCloudCpp.podspec
include/braincloud/BrainCloudGroup.h
include/braincloud/BrainCloudSocialLeaderboard.h
include/braincloud/OperationParam.h
include/braincloud/ServiceOperation.h
include/braincloud/internal/DefaultBrainCloudComms.h
src/BrainCloudClient.cpp
src/BrainCloudGroup.cpp
src/BrainCloudSocialLeaderboard.cpp
src/DefaultBrainCloudComms.cpp
src/OperationParam.cpp
src/ServiceOperation.cpp
tests/src/TestBCAuth.cpp
tests/src/TestBCAuth.h
tests/src/TestBCGroup.cpp
tests/src/TestBCGroup.h
tests/src/TestBCRTTComms.cpp
tests/src/TestBCSocialLeaderboard.cpp

* Added missing Android libs
* Updated version
* UpdateEntityIndexedId() added
* 4.0 Api calls
* quick adjustment to function
* RTT refactoring cpp (#80)
* resetUniversalIdPassword calls
* Cancel Lobby, and other fixes
* Readme update
* Adding guard so profileId and SessionId only saved for Auth and Identity
* Develop (#81)
* Added missing Android libs
* Updated version
* UpdateEntityIndexedId() added
* 4.0 Api calls
* quick adjustment to function
* RTT refactoring cpp (#80)
* resetUniversalIdPassword calls
* Cancel Lobby, and other fixes
* Readme update
* Adding guard so profileId and SessionId only saved for Auth and Identity
* updating versions of lib for release
* extra line addition
* updating pod version
* bad sig fixes and tests
* fixing up badSig tests
* making quick fixes and …

release 4.1.0  (#88)

---

tests/src/TestGUID.cpp

Apple uses Capital letters, other platforms might do other things.

Fixed GUID test on MaxOS

---

BrainCloudCpp.podspec
include/braincloud/BrainCloudCustomEntity.h
src/apple/AppleWebSocket.mm

* updating podspec
* Fixed issue with insertion of port in websocket URL in ObjC
Co-authored-by: David St-Louis <davidstl@bitheads.com>
Co-authored-by: Jonathan McCaffrey <jonmcc.0723@gmail.com>
Co-authored-by: pascalf1309 <54288832+pascalf1309@users.noreply.github.com>

4.3.5.1WebsocketPatch (#108)

---

include/braincloud/BrainCloudAuthentication.h
include/braincloud/BrainCloudCustomEntity.h
include/braincloud/BrainCloudIdentity.h
include/braincloud/OperationParam.h
include/braincloud/ServiceOperation.h
src/BrainCloudAuthentication.cpp
src/BrainCloudCustomEntity.cpp
src/BrainCloudIdentity.cpp
src/OperationParam.cpp
src/ServiceOperation.cpp
tests/src/TestBCAuth.cpp

made some additional changes for compatibility with Xcode

Release4.4

---

include/braincloud/BrainCloudAuthentication.h
include/braincloud/BrainCloudCustomEntity.h
include/braincloud/BrainCloudIdentity.h
include/braincloud/OperationParam.h
include/braincloud/ServiceOperation.h
src/BrainCloudAuthentication.cpp
src/BrainCloudCustomEntity.cpp
src/BrainCloudIdentity.cpp
src/OperationParam.cpp
src/ServiceOperation.cpp
tests/src/TestBCAuth.cpp

* pushing first batch of changes and unit tests
* adding the last changes required for release 4.4

Release 4.4 (#110)

---

include/braincloud/BrainCloudIdentity.h
include/braincloud/BrainCloudPlayerState.h
include/braincloud/BrainCloudScript.h
include/braincloud/BrainCloudWrapper.h
include/braincloud/OperationParam.h
include/braincloud/ServiceOperation.h
src/BrainCloudIdentity.cpp
src/BrainCloudPlayerState.cpp
src/BrainCloudScript.cpp
src/BrainCloudWrapper.cpp
src/OperationParam.cpp
src/ServiceOperation.cpp
tests/src/TestBCPlayerState.cpp
tests/src/TestBCScript.cpp

-Implemented missed apis with unit tests

4.4 api update

---

solutions/mac/BrainCloudCpp.xcodeproj/project.pbxproj

I dont think we still use that project. But updated it in case

updated xcode project

---

CMakeLists.txt
include/braincloud/BrainCloudClient.h
include/braincloud/BrainCloudRelay.h
include/braincloud/BrainCloudWrapper.h
include/braincloud/IRelayCallback.h
include/braincloud/IRelayConnectCallback.h
include/braincloud/IRelaySystemCallback.h
include/braincloud/RelayChannel.h
include/braincloud/RelayConnectionType.h
include/braincloud/internal/RelayComms.h
src/BrainCloudClient.cpp
src/BrainCloudRelay.cpp
src/RTTComms.cpp
src/RelayComms.cpp

Relay Service and Comms access, but will throw error because removed half working WS protocol.

Relay Comms - No protocols

---

include/braincloud/BrainCloudSocialLeaderboard.h
include/braincloud/ServiceOperation.h
src/BrainCloudSocialLeaderboard.cpp
src/ServiceOperation.cpp
tests/src/TestBCSocialLeaderboard.cpp

adding getPlayerScores to leaderboard service and unit test

adding getPlayerScores

---

include/braincloud/BrainCloudClient.h
include/braincloud/BrainCloudWrapper.h
tests/src/TestBCSocialLeaderboard.cpp

SocialLeaderboard->Leaderboard

Making Leaderboard service patch

---

include/braincloud/internal/DefaultWebSocket.h
src/DefaultWebSocket.cpp
tests/src/TestBCLobby.cpp
tests/src/TestBCLobby.h
tests/src/TestFixtureBase.h

Also fixed a websocket bug while doing this preventing to run 2 BC instances in separate threads (Or even single thread)

Added a functional test for Join+Create lobby with 2 users

---

tests/src/TestBCAuth.cpp

- Disabling test and adding comment that it is an unfinished feature.

Disable AuthManualRedirect

---

include/braincloud/BrainCloudWrapper.h
src/BrainCloudWrapper.cpp

Bug fix reconnect fails after user logs out

---

include/braincloud/internal/DefaultWebSocket.h
include/braincloud/internal/RTTComms.h
include/braincloud/internal/apple/AppleWebSocket.h
lib/apple/sskeychain/SSKeychain/SSKeychainQuery.m
src/DefaultWebSocket.cpp
src/RTTComms.cpp
src/RelayComms.cpp
src/apple/AppleWebSocket.mm
src/nix/cURLFileUploader.cpp
src/nix/cURLLoader.cpp

Fixes build error on objective

targetwatch fix for objc

---

CMakeLists.txt
include/braincloud/BrainCloudBlockchain.h
include/braincloud/BrainCloudClient.h
include/braincloud/BrainCloudWrapper.h
include/braincloud/OperationParam.h
include/braincloud/ServiceName.h
include/braincloud/ServiceOperation.h
src/BrainCloudBlockchain.cpp
src/BrainCloudClient.cpp
src/OperationParam.cpp
src/ServiceName.cpp
src/ServiceOperation.cpp
tests/src/TestBCBlockchain.cpp
tests/src/TestBCBlockchain.h

BCLOUD-3011

---

CMakeLists.txt
src/DefaultWebSocket.cpp

This fixes intermittent RTT connection fails on certain devices and emulators

BCLOUD-3058

---

Gemfile.lock
include/braincloud/http_codes.h
src/apple/nsFileUploader.mm
src/apple/nsURLLoader.mm

namespace added to resolve objective-c multiple declaration

BCLOUD-3400

---

BrainCloudCpp.podspec
include/braincloud/internal/DefaultWebSocket.h
include/braincloud/internal/RTTComms.h
include/braincloud/internal/RelayComms.h
include/braincloud/internal/apple/AppleWebSocket.h
src/apple/AppleWebSocket.mm

build for watch OS deployment target

BCLOUD-3431

---

BrainCloudCpp.podspec
src/BrainCloudClient.cpp

update version for 4.13.2

---

tests/src/TestBCWrapper.cpp

Bcloud 6698 logout

---

include/braincloud/BrainCloudAsyncMatch.h
include/braincloud/ServiceOperation.h
src/BrainCloudAsyncMatch.cpp
src/ServiceOperation.cpp
tests/src/TestBCAsyncMatch.cpp

Add UpdateMatchStateCurrentTurn API

Bcloud 8023 asyncmatch api

---

include/braincloud/BrainCloudEvent.h
include/braincloud/BrainCloudMessaging.h
include/braincloud/BrainCloudScript.h
include/braincloud/BrainCloudSocialLeaderboard.h
include/braincloud/BrainCloudTournament.h
src/BrainCloudEvent.cpp
src/BrainCloudMessaging.cpp
src/BrainCloudScript.cpp
src/BrainCloudSocialLeaderboard.cpp
src/BrainCloudTournament.cpp

Tested against each suite and there was no edits needed for the unit tests. Ran locally to confirm and everything passed.

Removing Deprecated Functions
